name: Automatically add asign PR author when PR is opened
on:
    pull_request:
        types: [opened, reopened]
jobs:
    assign-author:
      runs-on: ubuntu-latest
      steps:
        - uses: toshimaru/auto-author-assign@v1.1.0
          with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
